// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eocean_sms_protos.proto

package io.graphenee.sms.proto;

public final class EoceanSmsConfigProtos {
  private EoceanSmsConfigProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gx_sms.ConfigMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string baseUrl = 1;</code>
     */
    boolean hasBaseUrl();
    /**
     * <code>optional string baseUrl = 1;</code>
     */
    java.lang.String getBaseUrl();
    /**
     * <code>optional string baseUrl = 1;</code>
     */
    com.google.protobuf.ByteString
        getBaseUrlBytes();

    /**
     * <code>optional string user = 2;</code>
     */
    boolean hasUser();
    /**
     * <code>optional string user = 2;</code>
     */
    java.lang.String getUser();
    /**
     * <code>optional string user = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserBytes();

    /**
     * <code>optional string pwd = 3;</code>
     */
    boolean hasPwd();
    /**
     * <code>optional string pwd = 3;</code>
     */
    java.lang.String getPwd();
    /**
     * <code>optional string pwd = 3;</code>
     */
    com.google.protobuf.ByteString
        getPwdBytes();

    /**
     * <code>optional string response = 4;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional string response = 4;</code>
     */
    java.lang.String getResponse();
    /**
     * <code>optional string response = 4;</code>
     */
    com.google.protobuf.ByteString
        getResponseBytes();
  }
  /**
   * Protobuf type {@code gx_sms.ConfigMessage}
   */
  public  static final class ConfigMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gx_sms.ConfigMessage)
      ConfigMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfigMessage.newBuilder() to construct.
    private ConfigMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigMessage() {
      baseUrl_ = "";
      user_ = "";
      pwd_ = "";
      response_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              baseUrl_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              user_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              pwd_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              response_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.graphenee.sms.proto.EoceanSmsConfigProtos.internal_static_gx_sms_ConfigMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.graphenee.sms.proto.EoceanSmsConfigProtos.internal_static_gx_sms_ConfigMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage.class, io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage.Builder.class);
    }

    private int bitField0_;
    public static final int BASEURL_FIELD_NUMBER = 1;
    private volatile java.lang.Object baseUrl_;
    /**
     * <code>optional string baseUrl = 1;</code>
     */
    public boolean hasBaseUrl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string baseUrl = 1;</code>
     */
    public java.lang.String getBaseUrl() {
      java.lang.Object ref = baseUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          baseUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string baseUrl = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBaseUrlBytes() {
      java.lang.Object ref = baseUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_FIELD_NUMBER = 2;
    private volatile java.lang.Object user_;
    /**
     * <code>optional string user = 2;</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string user = 2;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          user_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string user = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PWD_FIELD_NUMBER = 3;
    private volatile java.lang.Object pwd_;
    /**
     * <code>optional string pwd = 3;</code>
     */
    public boolean hasPwd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string pwd = 3;</code>
     */
    public java.lang.String getPwd() {
      java.lang.Object ref = pwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pwd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pwd = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPwdBytes() {
      java.lang.Object ref = pwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSE_FIELD_NUMBER = 4;
    private volatile java.lang.Object response_;
    /**
     * <code>optional string response = 4;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string response = 4;</code>
     */
    public java.lang.String getResponse() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          response_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string response = 4;</code>
     */
    public com.google.protobuf.ByteString
        getResponseBytes() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        response_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, baseUrl_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, user_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, pwd_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, response_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, baseUrl_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, user_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, pwd_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, response_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage)) {
        return super.equals(obj);
      }
      io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage other = (io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage) obj;

      boolean result = true;
      result = result && (hasBaseUrl() == other.hasBaseUrl());
      if (hasBaseUrl()) {
        result = result && getBaseUrl()
            .equals(other.getBaseUrl());
      }
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      result = result && (hasPwd() == other.hasPwd());
      if (hasPwd()) {
        result = result && getPwd()
            .equals(other.getPwd());
      }
      result = result && (hasResponse() == other.hasResponse());
      if (hasResponse()) {
        result = result && getResponse()
            .equals(other.getResponse());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBaseUrl()) {
        hash = (37 * hash) + BASEURL_FIELD_NUMBER;
        hash = (53 * hash) + getBaseUrl().hashCode();
      }
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      if (hasPwd()) {
        hash = (37 * hash) + PWD_FIELD_NUMBER;
        hash = (53 * hash) + getPwd().hashCode();
      }
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gx_sms.ConfigMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gx_sms.ConfigMessage)
        io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.graphenee.sms.proto.EoceanSmsConfigProtos.internal_static_gx_sms_ConfigMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.graphenee.sms.proto.EoceanSmsConfigProtos.internal_static_gx_sms_ConfigMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage.class, io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage.Builder.class);
      }

      // Construct using io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        baseUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        user_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        pwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        response_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.graphenee.sms.proto.EoceanSmsConfigProtos.internal_static_gx_sms_ConfigMessage_descriptor;
      }

      @java.lang.Override
      public io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage getDefaultInstanceForType() {
        return io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage.getDefaultInstance();
      }

      @java.lang.Override
      public io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage build() {
        io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage buildPartial() {
        io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage result = new io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.baseUrl_ = baseUrl_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.user_ = user_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pwd_ = pwd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.response_ = response_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage) {
          return mergeFrom((io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage other) {
        if (other == io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage.getDefaultInstance()) return this;
        if (other.hasBaseUrl()) {
          bitField0_ |= 0x00000001;
          baseUrl_ = other.baseUrl_;
          onChanged();
        }
        if (other.hasUser()) {
          bitField0_ |= 0x00000002;
          user_ = other.user_;
          onChanged();
        }
        if (other.hasPwd()) {
          bitField0_ |= 0x00000004;
          pwd_ = other.pwd_;
          onChanged();
        }
        if (other.hasResponse()) {
          bitField0_ |= 0x00000008;
          response_ = other.response_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object baseUrl_ = "";
      /**
       * <code>optional string baseUrl = 1;</code>
       */
      public boolean hasBaseUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string baseUrl = 1;</code>
       */
      public java.lang.String getBaseUrl() {
        java.lang.Object ref = baseUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            baseUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string baseUrl = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBaseUrlBytes() {
        java.lang.Object ref = baseUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          baseUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string baseUrl = 1;</code>
       */
      public Builder setBaseUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        baseUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string baseUrl = 1;</code>
       */
      public Builder clearBaseUrl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        baseUrl_ = getDefaultInstance().getBaseUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string baseUrl = 1;</code>
       */
      public Builder setBaseUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        baseUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object user_ = "";
      /**
       * <code>optional string user = 2;</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string user = 2;</code>
       */
      public java.lang.String getUser() {
        java.lang.Object ref = user_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            user_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserBytes() {
        java.lang.Object ref = user_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          user_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user = 2;</code>
       */
      public Builder setUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        user_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user = 2;</code>
       */
      public Builder clearUser() {
        bitField0_ = (bitField0_ & ~0x00000002);
        user_ = getDefaultInstance().getUser();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user = 2;</code>
       */
      public Builder setUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        user_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pwd_ = "";
      /**
       * <code>optional string pwd = 3;</code>
       */
      public boolean hasPwd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string pwd = 3;</code>
       */
      public java.lang.String getPwd() {
        java.lang.Object ref = pwd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pwd_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pwd = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPwdBytes() {
        java.lang.Object ref = pwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pwd = 3;</code>
       */
      public Builder setPwd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        pwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pwd = 3;</code>
       */
      public Builder clearPwd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pwd_ = getDefaultInstance().getPwd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pwd = 3;</code>
       */
      public Builder setPwdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        pwd_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object response_ = "";
      /**
       * <code>optional string response = 4;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string response = 4;</code>
       */
      public java.lang.String getResponse() {
        java.lang.Object ref = response_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            response_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string response = 4;</code>
       */
      public com.google.protobuf.ByteString
          getResponseBytes() {
        java.lang.Object ref = response_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          response_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string response = 4;</code>
       */
      public Builder setResponse(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string response = 4;</code>
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000008);
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }
      /**
       * <code>optional string response = 4;</code>
       */
      public Builder setResponseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        response_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gx_sms.ConfigMessage)
    }

    // @@protoc_insertion_point(class_scope:gx_sms.ConfigMessage)
    private static final io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage();
    }

    public static io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ConfigMessage>
        PARSER = new com.google.protobuf.AbstractParser<ConfigMessage>() {
      @java.lang.Override
      public ConfigMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfigMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.graphenee.sms.proto.EoceanSmsConfigProtos.ConfigMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gx_sms_ConfigMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gx_sms_ConfigMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027eocean_sms_protos.proto\022\006gx_sms\"M\n\rCon" +
      "figMessage\022\017\n\007baseUrl\030\001 \001(\t\022\014\n\004user\030\002 \001(" +
      "\t\022\013\n\003pwd\030\003 \001(\t\022\020\n\010response\030\004 \001(\tB/\n\026io.g" +
      "raphenee.sms.protoB\025EoceanSmsConfigProto" +
      "s"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gx_sms_ConfigMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gx_sms_ConfigMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gx_sms_ConfigMessage_descriptor,
        new java.lang.String[] { "BaseUrl", "User", "Pwd", "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
